---
name: PostgreSQL Service Example
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [25, 26]
        postgres: ['14', '15', '16beta1']
    steps:
      - uses: actions/checkout@v3
      - run: sudo docker-compose up --detached
        env:
          POSTGRES_VERSION: ${{matrix.postgres}}
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
